import type { GameInfo } from '../types/game';

/**
 * Complete registry of all 15 games in the TONPLAY platform.
 *
 * Phase 1 launch: Only `flappy-rocket` is enabled.
 * Remaining games will be enabled incrementally in subsequent phases.
 *
 * Wager range: 10-1000 tickets for all games.
 * Max scores vary per game based on difficulty and expected session length.
 */
export const GAME_LIST: GameInfo[] = [
  // ── Arcade ──────────────────────────────────────────────────────────────
  {
    slug: 'neon-runner',
    name: 'Neon Runner',
    description: 'Dash through a neon-lit cityscape, dodge obstacles, and collect power-ups.',
    thumbnailUrl: '/games/neon-runner/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 500,
    category: 'arcade',
    enabled: true,
  },
  {
    slug: 'flappy-rocket',
    name: 'Flappy Rocket',
    description: 'Navigate your rocket through asteroid fields. Tap to thrust, avoid collisions.',
    thumbnailUrl: '/games/flappy-rocket/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 200,
    category: 'arcade',
    enabled: true,
  },
  {
    slug: 'snake-arena',
    name: 'Snake Arena',
    description: 'Classic snake gameplay with competitive scoring and power-up pickups.',
    thumbnailUrl: '/games/snake-arena/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 300,
    category: 'arcade',
    enabled: true,
  },
  {
    slug: 'pixel-blaster',
    name: 'Pixel Blaster',
    description: 'Retro-style space shooter. Destroy waves of enemies for high scores.',
    thumbnailUrl: '/games/pixel-blaster/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 1000,
    category: 'arcade',
    enabled: true,
  },
  {
    slug: 'fruit-slash',
    name: 'Fruit Slash',
    description: 'Swipe to slice flying fruit while avoiding bombs. Chain combos for bonus points.',
    thumbnailUrl: '/games/fruit-slash/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 400,
    category: 'arcade',
    enabled: true,
  },

  // ── Casino ──────────────────────────────────────────────────────────────
  {
    slug: 'slot-spin',
    name: 'Slot Spin',
    description: 'Classic 3-reel slot machine with provably fair outcomes.',
    thumbnailUrl: '/games/slot-spin/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 50,
    category: 'casino',
    enabled: true,
  },
  {
    slug: 'dice-duel',
    name: 'Dice Duel',
    description: 'Roll the dice and bet on outcomes. Simple, fast, provably fair.',
    thumbnailUrl: '/games/dice-duel/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 36,
    category: 'casino',
    enabled: true,
  },
  {
    slug: 'coin-train',
    name: 'Coin Train',
    description: 'Watch the multiplier climb and cash out before the train derails.',
    thumbnailUrl: '/games/coin-train/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 100,
    category: 'casino',
    enabled: true,
  },

  // ── Physics ─────────────────────────────────────────────────────────────
  {
    slug: 'coin-dropper',
    name: 'Coin Dropper',
    description: 'Drop coins into a physics-based machine. Land on multiplier slots to win big.',
    thumbnailUrl: '/games/coin-dropper/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 150,
    category: 'physics',
    enabled: true,
  },
  {
    slug: 'plinko-drop',
    name: 'Plinko Drop',
    description: 'Release a ball from the top and watch it bounce through pegs to a prize slot.',
    thumbnailUrl: '/games/plinko-drop/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 100,
    category: 'physics',
    enabled: true,
  },
  {
    slug: 'tower-stack',
    name: 'Tower Stack',
    description: 'Stack blocks as high as you can. Precision timing determines your score.',
    thumbnailUrl: '/games/tower-stack/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 100,
    category: 'physics',
    enabled: true,
  },
  {
    slug: 'bubble-pop',
    name: 'Bubble Pop',
    description: 'Shoot bubbles to match colors and clear the board before time runs out.',
    thumbnailUrl: '/games/bubble-pop/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 250,
    category: 'physics',
    enabled: true,
  },

  // ── Puzzle ──────────────────────────────────────────────────────────────
  {
    slug: 'block-crush',
    name: 'Block Crush',
    description: 'Match and crush colored blocks in this fast-paced puzzle challenge.',
    thumbnailUrl: '/games/block-crush/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 500,
    category: 'puzzle',
    enabled: true,
  },
  {
    slug: 'memory-cards',
    name: 'Memory Cards',
    description: 'Flip cards to find matching pairs. Fewer flips means a higher score.',
    thumbnailUrl: '/games/memory-cards/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 100,
    category: 'puzzle',
    enabled: true,
  },
  {
    slug: 'rhythm-tap',
    name: 'Rhythm Tap',
    description: 'Tap to the beat of the music. Perfect timing earns maximum points.',
    thumbnailUrl: '/games/rhythm-tap/thumb.webp',
    minWager: 10,
    maxWager: 1000,
    maxScore: 300,
    category: 'puzzle',
    enabled: true,
  },
];
